In [12]:
import numpy as np
x = np.load("MNIST_train.npy")
y = np.load("MNIST_label.npy")


In [5]:
x.shape

(10, 14, 14)

In [13]:
y.shape

(10, 1, 10)

In [11]:
np.savetxt("x1.txt",x[1], delimiter=',',fmt = "%03d", footer='\n')

In [14]:
y[1]

array([[ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [7]:
x[2]

array([[   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,
           0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,
           0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,
           0.  ,  157.75,   47.75,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,
          11.25,  192.5 ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,
          71.5 ,  137.75,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,
         158.75,  102.75,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,   14.25,
         209.  ,   21.25,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ],

In [9]:
x[3]

array([[   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,
           0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,
           0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ,  112.25,
         239.75,   34.5 ,    0.  ,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,    0.  ,   80.25,  237.5 ,
         252.  ,   96.25,   15.5 ,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    0.  ,   45.5 ,  253.  ,  252.  ,
         247.75,  244.25,  194.25,    0.  ,    0.  ,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,    8.  ,  191.5 ,  252.  ,  214.75,
          58.5 ,   55.25,  245.75,  115.25,    1.25,    0.  ,    0.  ],
       [   0.  ,    0.  ,    0.  ,   18.5 ,  251.  ,  168.  ,    5.  ,
           0.  ,    0.  ,  147.75,  252.  ,   17.5 ,    0.  ,    0.  ],